/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package callcenter;

import java.awt.Color;
import static java.awt.Color.blue;
import static java.awt.Color.green;
import static java.awt.Color.red;

/**
 *
 * @author Pooja
 */
public class Temp extends javax.swing.JFrame {

    /**
     * Creates new form Temp
     */
    public Temp() {
        initComponents();
        //jTextArea1.setBackground(new Color(red, green, blue, alpha));
        scroll.setOpaque(false);
        scroll.getViewport().setOpaque(false);
        scroll.setBorder(null);
        scroll.setViewportBorder(null);
        textAreaImage.setOpaque(true);
        textAreaImage.setBorder(null);
        textAreaImage.setBackground(new Color(0,0,0,10));
        textAreaImage.setText("Hey qweiruifjkffkajad \n hsgjagduaydtua");
        textAreaImage.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutUsTextP = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        textAreaImage = new javax.swing.JTextArea();
        imageL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1370, 580));
        getContentPane().setLayout(null);

        aboutUsTextP.setBackground(new java.awt.Color(153, 153, 153));
        aboutUsTextP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aboutUsTextP.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ABOUT US");
        aboutUsTextP.add(jLabel1);
        jLabel1.setBounds(10, 10, 370, 30);

        getContentPane().add(aboutUsTextP);
        aboutUsTextP.setBounds(0, 9, 1370, 40);

        scroll.setBackground(new Color(0,0,10));
        scroll.setBorder(null);
        scroll.setEnabled(false);
        scroll.setOpaque(false);

        textAreaImage.setBackground(new Color(0,0,10));
        textAreaImage.setColumns(20);
        textAreaImage.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        textAreaImage.setForeground(new java.awt.Color(255, 0, 0));
        textAreaImage.setRows(5);
        textAreaImage.setOpaque(false);
        scroll.setViewportView(textAreaImage);

        getContentPane().add(scroll);
        scroll.setBounds(70, 90, 450, 330);

        imageL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/about-us1.jpg"))); // NOI18N
        getContentPane().add(imageL);
        imageL.setBounds(10, 70, 1330, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Temp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Temp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Temp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Temp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Temp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutUsTextP;
    private javax.swing.JLabel imageL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextArea textAreaImage;
    // End of variables declaration//GEN-END:variables
}
